version: '3'

services:
  php8.2:
    build:
      context: ./php8.2
    hostname: php8.2
    ports:
      - "10001:9000"
      - "6002:6002"
    volumes:
      - ../projects/:/var/www/html/
      - ./php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php8.2/php.ini:/usr/local/etc/php/php.ini

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    ports:
      - "80:80"
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ../projects/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.2
    networks:
      - backend
  mysql8.1:
    platform: linux/x86_64
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    depends_on:
      - php8.2
    volumes:
      - ./mysql8_1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql8.1
      #PMA_PORT: 3307
      #PMA_USER: root
      #PMA_PASSWORD: "12345678"
    depends_on:
      - mysql8.1
    ports:
      - "8080:80"
    networks:
      - backend
networks:
  backend:
    driver: bridge